[package]
name = "comp_macro"
version = "0.1.0"
edition = "2021"
authors = ["Ammar Farhan Mohamad Rizam <ammarfmr11@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.92"
quote = "1.0.38"
syn = { version =  "2.0.96", features = ["extra-traits", "full"] }
